In [224]:
n = 20

print('meu nome é rafael e tenho {} anos'.format(n))

meu nome é rafael e tenho 20 anos

In [225]:
import pandas as pd

tabela  = pd.read_csv('archive/all_indices_data.csv')
display(tabela)

,date,open,high,low,close,volume,ticker
0,1927-12-30,17.660000,17.660000,17.660000,17.660000,0.0,^GSPC
1,1928-01-03,17.760000,17.760000,17.760000,17.760000,0.0,^GSPC
2,1928-01-04,17.719999,17.719999,17.719999,17.719999,0.0,^GSPC
3,1928-01-05,17.549999,17.549999,17.549999,17.549999,0.0,^GSPC
4,1928-01-06,17.660000,17.660000,17.660000,17.660000,0.0,^GSPC
...,...,...,...,...,...,...,...
283905,2023-08-10,4050.120117,4174.439941,4040.540039,4147.879883,0.0,^JN0U.JO
283906,2023-08-11,4117.830078,4119.009766,4051.540039,4066.860107,0.0,^JN0U.JO
283907,2023-08-14,4042.120117,4061.399902,3945.500000,3979.110107,0.0,^JN0U.JO
283908,2023-08-15,3983.780029,3994.810059,3906.199951,3933.360107,0.0,^JN0U.JO
283909,2023-08-16,3944.840088,3944.840088,3867.570068,3911.010010,0.0,^JN0U.JO

In [226]:
tabela['resultado'] = tabela['close'] - tabela['open']
display(tabela)

,date,open,high,low,close,volume,ticker,resultado
0,1927-12-30,17.660000,17.660000,17.660000,17.660000,0.0,^GSPC,0.000000
1,1928-01-03,17.760000,17.760000,17.760000,17.760000,0.0,^GSPC,0.000000
2,1928-01-04,17.719999,17.719999,17.719999,17.719999,0.0,^GSPC,0.000000
3,1928-01-05,17.549999,17.549999,17.549999,17.549999,0.0,^GSPC,0.000000
4,1928-01-06,17.660000,17.660000,17.660000,17.660000,0.0,^GSPC,0.000000
...,...,...,...,...,...,...,...,...
283905,2023-08-10,4050.120117,4174.439941,4040.540039,4147.879883,0.0,^JN0U.JO,97.759766
283906,2023-08-11,4117.830078,4119.009766,4051.540039,4066.860107,0.0,^JN0U.JO,-50.969971
283907,2023-08-14,4042.120117,4061.399902,3945.500000,3979.110107,0.0,^JN0U.JO,-63.010010
283908,2023-08-15,3983.780029,3994.810059,3906.199951,3933.360107,0.0,^JN0U.JO,-50.419922
283909,2023-08-16,3944.840088,3944.840088,3867.570068,3911.010010,0.0,^JN0U.JO,-33.830078

In [227]:
tabela = tabela[tabela['open'] != 0]

In [228]:
tabela = tabela[tabela['volume'] > 10000]
display(tabela)

,date,open,high,low,close,volume,ticker,resultado
5496,1950-01-03,16.660000,16.660000,16.660000,16.660000,1260000.0,^GSPC,0.000000
5497,1950-01-04,16.850000,16.850000,16.850000,16.850000,1890000.0,^GSPC,0.000000
5498,1950-01-05,16.930000,16.930000,16.930000,16.930000,2550000.0,^GSPC,0.000000
5499,1950-01-06,16.980000,16.980000,16.980000,16.980000,2010000.0,^GSPC,0.000000
5500,1950-01-09,17.080000,17.080000,17.080000,17.080000,2520000.0,^GSPC,0.000000
...,...,...,...,...,...,...,...,...
282432,2023-08-10,1904.540039,1917.839966,1904.540039,1914.589966,48197000.0,^TA125.TA,10.049927
282433,2023-08-13,1910.550049,1910.670044,1883.599976,1887.339966,18759200.0,^TA125.TA,-23.210083
282434,2023-08-14,1891.199951,1899.829956,1871.719971,1873.449951,57170100.0,^TA125.TA,-17.750000
282435,2023-08-15,1881.949951,1882.550049,1857.000000,1867.449951,57457200.0,^TA125.TA,-14.500000
282436,2023-08-16,1872.229980,1879.060059,1858.930054,1862.339966,38272300.0,^TA125.TA,-9.890015

In [229]:
tabela = tabela[tabela['resultado'] != 0.000000]
display(tabela)

,date,open,high,low,close,volume,ticker,resultado
13602,1982-04-20,115.800003,117.139999,114.830002,115.440002,54610000.0,^GSPC,-0.360001
13603,1982-04-21,115.480003,115.870003,115.300003,115.720001,57820000.0,^GSPC,0.239998
13604,1982-04-22,115.720001,117.250000,115.720001,117.190002,64470000.0,^GSPC,1.470001
13605,1982-04-23,118.019997,118.639999,117.190002,118.639999,71840000.0,^GSPC,0.620003
13606,1982-04-26,118.940002,119.330002,118.250000,119.260002,60500000.0,^GSPC,0.320000
...,...,...,...,...,...,...,...,...
282432,2023-08-10,1904.540039,1917.839966,1904.540039,1914.589966,48197000.0,^TA125.TA,10.049927
282433,2023-08-13,1910.550049,1910.670044,1883.599976,1887.339966,18759200.0,^TA125.TA,-23.210083
282434,2023-08-14,1891.199951,1899.829956,1871.719971,1873.449951,57170100.0,^TA125.TA,-17.750000
282435,2023-08-15,1881.949951,1882.550049,1857.000000,1867.449951,57457200.0,^TA125.TA,-14.500000
282436,2023-08-16,1872.229980,1879.060059,1858.930054,1862.339966,38272300.0,^TA125.TA,-9.890015

In [230]:
display(tabela.groupby("ticker").sum(numeric_only=True))
tabela_aux = tabela.groupby("ticker").sum(numeric_only=True)

,open,high,low,close,volume,resultado
ticker,,,,,,
000001.SS,1.312753e+07,1.324313e+07,1.300942e+07,1.314123e+07,7.974710e+08,13708.437195
399001.SZ,4.638651e+07,4.687029e+07,4.589342e+07,4.642165e+07,2.188055e+09,35139.361190
^AORD,2.757949e+07,2.772030e+07,2.744024e+07,2.758286e+07,4.704332e+12,3369.274902
^AXJO,9.844824e+06,9.894870e+06,9.794987e+06,9.845925e+06,2.211527e+11,1101.606445
^BFX,1.157891e+07,1.164548e+07,1.150248e+07,1.157659e+07,7.372561e+10,-2319.747314
^BSESN,8.238647e+07,8.291109e+07,8.168101e+07,8.229181e+07,3.922829e+08,-94659.721436
^BVSP,2.961823e+08,2.991616e+08,2.932083e+08,2.962578e+08,4.523636e+10,75482.000000
^DJI,1.114440e+08,1.121122e+08,1.107498e+08,1.114691e+08,1.524128e+12,25143.798340
^FCHI,2.267286e+07,2.281820e+07,2.251143e+07,2.267003e+07,5.468369e+11,-2833.789551
^FTSE,3.765723e+07,3.790775e+07,3.739893e+07,3.765765e+07,6.592006e+12,421.897461
^GDAXI,5.091391e+07,5.127626e+07,5.051771e+07,5.091126e+07,6.169547e+11,-2645.668457
^GSPC,1.356794e+07,1.364872e+07,1.348180e+07,1.357083e+07,2.094387e+13,2891.774567
^GSPTSE,9.332808e+07,9.375540e+07,9.283286e+07,9.331564e+07,1.144321e+12,-12441.154261
^HSI,1.120630e+08,1.127424e+08,1.112259e+08,1.120061e+08,8.409380e+12,-56901.760742
^IXIC,3.192484e+07,3.214977e+07,3.167005e+07,3.192395e+07,1.532538e+13,-891.945160
^JKSE,2.062958e+07,2.074718e+07,2.049578e+07,2.062988e+07,3.700860e+11,294.822449
^KLSE,7.856196e+06,7.888406e+06,7.820087e+06,7.856650e+06,7.647878e+11,454.596252
^KS11,1.044816e+07,1.051124e+07,1.036966e+07,1.044284e+07,2.886069e+09,-5319.116547
^MERV,3.471800e+03,3.522200e+03,3.471800e+03,3.513300e+03,1.740000e+04,41.500000
^MXX,1.851713e+08,1.864060e+08,1.839031e+08,1.851940e+08,8.870292e+11,22705.335938
^N100,3.947290e+06,3.970641e+06,3.921518e+06,3.946939e+06,1.178710e+12,-350.422424
^N225,8.495221e+07,8.544053e+07,8.441782e+07,8.493964e+07,5.916878e+11,-12572.690430
^NYA,5.200788e+07,5.229299e+07,5.169439e+07,5.201262e+07,1.874427e+13,4741.749512
^NZ50,2.873509e+07,2.885530e+07,2.861805e+07,2.874348e+07,1.528650e+11,8393.347900
^RUT,6.837443e+06,6.886413e+06,6.784083e+06,6.838524e+06,2.077904e+13,1080.094513
^STI,1.397472e+07,1.404226e+07,1.389968e+07,1.396971e+07,9.252937e+11,-5011.560730
^STOXX50E,8.697106e+06,8.754305e+06,8.636742e+06,8.697621e+06,1.103709e+11,515.573730
^TA125.TA,3.688435e+06,3.704862e+06,3.669653e+06,3.687617e+06,2.516213e+11,-817.976746
^TWII,4.664910e+07,4.687459e+07,4.636906e+07,4.661747e+07,1.649947e+10,-31631.184748
^XAX,4.892264e+06,4.923698e+06,4.849100e+06,4.894403e+06,1.827264e+09,2138.940796

In [231]:
tabela_aux = tabela_aux.sort_values('resultado', ascending=False)
display(tabela_aux)

,open,high,low,close,volume,resultado
ticker,,,,,,
^BVSP,2.961823e+08,2.991616e+08,2.932083e+08,2.962578e+08,4.523636e+10,75482.000000
399001.SZ,4.638651e+07,4.687029e+07,4.589342e+07,4.642165e+07,2.188055e+09,35139.361190
^DJI,1.114440e+08,1.121122e+08,1.107498e+08,1.114691e+08,1.524128e+12,25143.798340
^MXX,1.851713e+08,1.864060e+08,1.839031e+08,1.851940e+08,8.870292e+11,22705.335938
000001.SS,1.312753e+07,1.324313e+07,1.300942e+07,1.314123e+07,7.974710e+08,13708.437195
^NZ50,2.873509e+07,2.885530e+07,2.861805e+07,2.874348e+07,1.528650e+11,8393.347900
^NYA,5.200788e+07,5.229299e+07,5.169439e+07,5.201262e+07,1.874427e+13,4741.749512
^AORD,2.757949e+07,2.772030e+07,2.744024e+07,2.758286e+07,4.704332e+12,3369.274902
^GSPC,1.356794e+07,1.364872e+07,1.348180e+07,1.357083e+07,2.094387e+13,2891.774567
^XAX,4.892264e+06,4.923698e+06,4.849100e+06,4.894403e+06,1.827264e+09,2138.940796
^AXJO,9.844824e+06,9.894870e+06,9.794987e+06,9.845925e+06,2.211527e+11,1101.606445
^RUT,6.837443e+06,6.886413e+06,6.784083e+06,6.838524e+06,2.077904e+13,1080.094513
^STOXX50E,8.697106e+06,8.754305e+06,8.636742e+06,8.697621e+06,1.103709e+11,515.573730
^KLSE,7.856196e+06,7.888406e+06,7.820087e+06,7.856650e+06,7.647878e+11,454.596252
^FTSE,3.765723e+07,3.790775e+07,3.739893e+07,3.765765e+07,6.592006e+12,421.897461
^JKSE,2.062958e+07,2.074718e+07,2.049578e+07,2.062988e+07,3.700860e+11,294.822449
^MERV,3.471800e+03,3.522200e+03,3.471800e+03,3.513300e+03,1.740000e+04,41.500000
^N100,3.947290e+06,3.970641e+06,3.921518e+06,3.946939e+06,1.178710e+12,-350.422424
^TA125.TA,3.688435e+06,3.704862e+06,3.669653e+06,3.687617e+06,2.516213e+11,-817.976746
^IXIC,3.192484e+07,3.214977e+07,3.167005e+07,3.192395e+07,1.532538e+13,-891.945160
^BFX,1.157891e+07,1.164548e+07,1.150248e+07,1.157659e+07,7.372561e+10,-2319.747314
^GDAXI,5.091391e+07,5.127626e+07,5.051771e+07,5.091126e+07,6.169547e+11,-2645.668457
^FCHI,2.267286e+07,2.281820e+07,2.251143e+07,2.267003e+07,5.468369e+11,-2833.789551
^STI,1.397472e+07,1.404226e+07,1.389968e+07,1.396971e+07,9.252937e+11,-5011.560730
^KS11,1.044816e+07,1.051124e+07,1.036966e+07,1.044284e+07,2.886069e+09,-5319.116547
^GSPTSE,9.332808e+07,9.375540e+07,9.283286e+07,9.331564e+07,1.144321e+12,-12441.154261
^N225,8.495221e+07,8.544053e+07,8.441782e+07,8.493964e+07,5.916878e+11,-12572.690430
^TWII,4.664910e+07,4.687459e+07,4.636906e+07,4.661747e+07,1.649947e+10,-31631.184748
^HSI,1.120630e+08,1.127424e+08,1.112259e+08,1.120061e+08,8.409380e+12,-56901.760742
^BSESN,8.238647e+07,8.291109e+07,8.168101e+07,8.229181e+07,3.922829e+08,-94659.721436

In [232]:
display(tabela_aux['resultado'].count())
tabela_positiva = tabela_aux[tabela_aux['resultado'] >=0]
tabela_negativa = tabela_aux[tabela_aux['resultado'] <0]


display(tabela_positiva['resultado'].count())
display(tabela_negativa['resultado'].count())

30

17

13

In [ ]:
print('Existe {}'.format())